
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
app:
  security:
    token:
      secret: youcannothackusbecausewehavestrongsecretkey
      expires-after-days: 1
  folder-path: C:\Users\User\IdeaProjects\news\src\main\resources\images\
server:
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /v3/api-docs
    enabled: true
